with fixtures (
  external_id,
  group_name,
  home_code,
  away_code,
  kickoff_at,
  venue,
  city,
  status,
  home_score,
  away_score
) as (
  values
    ('group-a-1', 'A', 'MEX', 'RSA', '2026-06-11T19:00:00Z'::timestamptz, 'Estadio Azteca', 'Mexico City', 'encerrado'::public.match_status, 2, 0),
    ('group-a-2', 'A', 'KOR', 'CZE', '2026-06-12T01:00:00Z'::timestamptz, 'SoFi Stadium', 'Los Angeles', 'encerrado'::public.match_status, 2, 1),
    ('group-b-1', 'B', 'CAN', 'BIH', '2026-06-12T19:00:00Z'::timestamptz, 'BMO Field', 'Toronto', 'encerrado'::public.match_status, 1, 1),
    ('group-d-1', 'D', 'USA', 'PAR', '2026-06-13T01:00:00Z'::timestamptz, 'SoFi Stadium', 'Los Angeles', 'encerrado'::public.match_status, 4, 1),
    ('group-c-1', 'C', 'HAI', 'SCO', '2026-06-13T16:00:00Z'::timestamptz, 'Gillette Stadium', 'Boston', 'agendado'::public.match_status, null, null),
    ('group-d-2', 'D', 'AUS', 'TUR', '2026-06-13T19:00:00Z'::timestamptz, 'BC Place', 'Vancouver', 'agendado'::public.match_status, null, null),
    ('group-c-2', 'C', 'BRA', 'MAR', '2026-06-13T22:00:00Z'::timestamptz, 'MetLife Stadium', 'New York/New Jersey', 'agendado'::public.match_status, null, null),
    ('group-b-2', 'B', 'QAT', 'SUI', '2026-06-14T01:00:00Z'::timestamptz, 'Levi''s Stadium', 'San Francisco Bay Area', 'agendado'::public.match_status, null, null),
    ('group-e-1', 'E', 'GER', 'CUW', '2026-06-14T19:00:00Z'::timestamptz, 'Lincoln Financial Field', 'Philadelphia', 'agendado'::public.match_status, null, null),
    ('group-f-1', 'F', 'NED', 'JPN', '2026-06-14T22:00:00Z'::timestamptz, 'AT&T Stadium', 'Dallas', 'agendado'::public.match_status, null, null),
    ('group-e-2', 'E', 'CIV', 'ECU', '2026-06-15T01:00:00Z'::timestamptz, 'NRG Stadium', 'Houston', 'agendado'::public.match_status, null, null),
    ('group-f-2', 'F', 'SWE', 'TUN', '2026-06-15T04:00:00Z'::timestamptz, 'Estadio BBVA', 'Monterrey', 'agendado'::public.match_status, null, null),
    ('group-g-1', 'G', 'BEL', 'EGY', '2026-06-15T16:00:00Z'::timestamptz, 'Rose Bowl', 'Los Angeles', 'agendado'::public.match_status, null, null),
    ('group-h-1', 'H', 'KSA', 'URU', '2026-06-15T19:00:00Z'::timestamptz, 'Hard Rock Stadium', 'Miami', 'agendado'::public.match_status, null, null),
    ('group-g-2', 'G', 'IRN', 'NZL', '2026-06-15T22:00:00Z'::timestamptz, 'BMO Field', 'Toronto', 'agendado'::public.match_status, null, null),
    ('group-h-2', 'H', 'ESP', 'CPV', '2026-06-16T01:00:00Z'::timestamptz, 'AT&T Stadium', 'Dallas', 'agendado'::public.match_status, null, null),
    ('group-i-1', 'I', 'FRA', 'SEN', '2026-06-16T19:00:00Z'::timestamptz, 'MetLife Stadium', 'New York/New Jersey', 'agendado'::public.match_status, null, null),
    ('group-j-1', 'J', 'ARG', 'ALG', '2026-06-16T22:00:00Z'::timestamptz, 'Arrowhead Stadium', 'Kansas City', 'agendado'::public.match_status, null, null),
    ('group-i-2', 'I', 'IRQ', 'NOR', '2026-06-17T01:00:00Z'::timestamptz, 'Lumen Field', 'Seattle', 'agendado'::public.match_status, null, null),
    ('group-j-2', 'J', 'AUT', 'JOR', '2026-06-17T04:00:00Z'::timestamptz, 'Levi''s Stadium', 'San Francisco Bay Area', 'agendado'::public.match_status, null, null),
    ('group-k-1', 'K', 'POR', 'COD', '2026-06-17T19:00:00Z'::timestamptz, 'NRG Stadium', 'Houston', 'agendado'::public.match_status, null, null),
    ('group-l-1', 'L', 'GHA', 'PAN', '2026-06-17T22:00:00Z'::timestamptz, 'Gillette Stadium', 'Boston', 'agendado'::public.match_status, null, null),
    ('group-k-2', 'K', 'UZB', 'COL', '2026-06-18T01:00:00Z'::timestamptz, 'MetLife Stadium', 'New York/New Jersey', 'agendado'::public.match_status, null, null),
    ('group-l-2', 'L', 'ENG', 'CRO', '2026-06-18T04:00:00Z'::timestamptz, 'BC Place', 'Vancouver', 'agendado'::public.match_status, null, null),
    ('group-b-3', 'B', 'BIH', 'SUI', '2026-06-18T19:00:00Z'::timestamptz, 'Mercedes-Benz Stadium', 'Atlanta', 'agendado'::public.match_status, null, null),
    ('group-a-3', 'A', 'RSA', 'CZE', '2026-06-18T22:00:00Z'::timestamptz, 'BC Place', 'Vancouver', 'agendado'::public.match_status, null, null),
    ('group-b-4', 'B', 'CAN', 'QAT', '2026-06-19T01:00:00Z'::timestamptz, 'Arrowhead Stadium', 'Kansas City', 'agendado'::public.match_status, null, null),
    ('group-a-4', 'A', 'MEX', 'KOR', '2026-06-19T04:00:00Z'::timestamptz, 'Estadio Akron', 'Guadalajara', 'agendado'::public.match_status, null, null),
    ('group-d-3', 'D', 'PAR', 'TUR', '2026-06-19T16:00:00Z'::timestamptz, 'Lincoln Financial Field', 'Philadelphia', 'agendado'::public.match_status, null, null),
    ('group-c-3', 'C', 'MAR', 'SCO', '2026-06-19T19:00:00Z'::timestamptz, 'Gillette Stadium', 'Boston', 'agendado'::public.match_status, null, null),
    ('group-d-4', 'D', 'USA', 'AUS', '2026-06-19T22:00:00Z'::timestamptz, 'Lumen Field', 'Seattle', 'agendado'::public.match_status, null, null),
    ('group-c-4', 'C', 'BRA', 'HAI', '2026-06-20T01:00:00Z'::timestamptz, 'Hard Rock Stadium', 'Miami', 'agendado'::public.match_status, null, null),
    ('group-f-3', 'F', 'JPN', 'TUN', '2026-06-20T16:00:00Z'::timestamptz, 'Mercedes-Benz Stadium', 'Atlanta', 'agendado'::public.match_status, null, null),
    ('group-e-3', 'E', 'CUW', 'ECU', '2026-06-20T19:00:00Z'::timestamptz, 'Lincoln Financial Field', 'Philadelphia', 'agendado'::public.match_status, null, null),
    ('group-f-4', 'F', 'NED', 'SWE', '2026-06-20T22:00:00Z'::timestamptz, 'Levi''s Stadium', 'San Francisco Bay Area', 'agendado'::public.match_status, null, null),
    ('group-e-4', 'E', 'GER', 'CIV', '2026-06-21T01:00:00Z'::timestamptz, 'NRG Stadium', 'Houston', 'agendado'::public.match_status, null, null),
    ('group-h-3', 'H', 'CPV', 'URU', '2026-06-21T16:00:00Z'::timestamptz, 'BMO Field', 'Toronto', 'agendado'::public.match_status, null, null),
    ('group-g-3', 'G', 'EGY', 'NZL', '2026-06-21T19:00:00Z'::timestamptz, 'MetLife Stadium', 'New York/New Jersey', 'agendado'::public.match_status, null, null),
    ('group-h-4', 'H', 'ESP', 'KSA', '2026-06-21T22:00:00Z'::timestamptz, 'AT&T Stadium', 'Dallas', 'agendado'::public.match_status, null, null),
    ('group-g-4', 'G', 'BEL', 'IRN', '2026-06-22T01:00:00Z'::timestamptz, 'SoFi Stadium', 'Los Angeles', 'agendado'::public.match_status, null, null),
    ('group-j-3', 'J', 'ALG', 'JOR', '2026-06-22T16:00:00Z'::timestamptz, 'MetLife Stadium', 'New York/New Jersey', 'agendado'::public.match_status, null, null),
    ('group-i-3', 'I', 'SEN', 'NOR', '2026-06-22T19:00:00Z'::timestamptz, 'Lincoln Financial Field', 'Philadelphia', 'agendado'::public.match_status, null, null),
    ('group-j-4', 'J', 'ARG', 'AUT', '2026-06-22T22:00:00Z'::timestamptz, 'Arrowhead Stadium', 'Kansas City', 'agendado'::public.match_status, null, null),
    ('group-i-4', 'I', 'FRA', 'IRQ', '2026-06-23T01:00:00Z'::timestamptz, 'Lumen Field', 'Seattle', 'agendado'::public.match_status, null, null),
    ('group-l-3', 'L', 'CRO', 'PAN', '2026-06-23T19:00:00Z'::timestamptz, 'BMO Field', 'Toronto', 'agendado'::public.match_status, null, null),
    ('group-k-3', 'K', 'COD', 'COL', '2026-06-23T22:00:00Z'::timestamptz, 'Hard Rock Stadium', 'Miami', 'agendado'::public.match_status, null, null),
    ('group-l-4', 'L', 'ENG', 'GHA', '2026-06-24T01:00:00Z'::timestamptz, 'AT&T Stadium', 'Dallas', 'agendado'::public.match_status, null, null),
    ('group-k-4', 'K', 'POR', 'UZB', '2026-06-24T04:00:00Z'::timestamptz, 'Estadio Azteca', 'Mexico City', 'agendado'::public.match_status, null, null),
    ('group-a-5', 'A', 'CZE', 'MEX', '2026-06-24T19:00:00Z'::timestamptz, 'NRG Stadium', 'Houston', 'agendado'::public.match_status, null, null),
    ('group-a-6', 'A', 'RSA', 'KOR', '2026-06-24T19:00:00Z'::timestamptz, 'Estadio Azteca', 'Mexico City', 'agendado'::public.match_status, null, null),
    ('group-b-5', 'B', 'BIH', 'QAT', '2026-06-24T23:00:00Z'::timestamptz, 'Levi''s Stadium', 'San Francisco Bay Area', 'agendado'::public.match_status, null, null),
    ('group-b-6', 'B', 'SUI', 'CAN', '2026-06-24T23:00:00Z'::timestamptz, 'BC Place', 'Vancouver', 'agendado'::public.match_status, null, null),
    ('group-c-5', 'C', 'SCO', 'BRA', '2026-06-25T02:00:00Z'::timestamptz, 'AT&T Stadium', 'Dallas', 'agendado'::public.match_status, null, null),
    ('group-c-6', 'C', 'MAR', 'HAI', '2026-06-25T02:00:00Z'::timestamptz, 'Lumen Field', 'Seattle', 'agendado'::public.match_status, null, null),
    ('group-d-5', 'D', 'TUR', 'USA', '2026-06-25T20:00:00Z'::timestamptz, 'Hard Rock Stadium', 'Miami', 'agendado'::public.match_status, null, null),
    ('group-d-6', 'D', 'PAR', 'AUS', '2026-06-25T20:00:00Z'::timestamptz, 'Arrowhead Stadium', 'Kansas City', 'agendado'::public.match_status, null, null),
    ('group-e-5', 'E', 'ECU', 'GER', '2026-06-26T00:00:00Z'::timestamptz, 'MetLife Stadium', 'New York/New Jersey', 'agendado'::public.match_status, null, null),
    ('group-e-6', 'E', 'CUW', 'CIV', '2026-06-26T00:00:00Z'::timestamptz, 'Estadio BBVA', 'Monterrey', 'agendado'::public.match_status, null, null),
    ('group-f-5', 'F', 'TUN', 'NED', '2026-06-26T03:00:00Z'::timestamptz, 'Estadio Akron', 'Guadalajara', 'agendado'::public.match_status, null, null),
    ('group-f-6', 'F', 'JPN', 'SWE', '2026-06-26T03:00:00Z'::timestamptz, 'Mercedes-Benz Stadium', 'Atlanta', 'agendado'::public.match_status, null, null),
    ('group-i-5', 'I', 'NOR', 'FRA', '2026-06-26T19:00:00Z'::timestamptz, 'Gillette Stadium', 'Boston', 'agendado'::public.match_status, null, null),
    ('group-i-6', 'I', 'SEN', 'IRQ', '2026-06-26T19:00:00Z'::timestamptz, 'BMO Field', 'Toronto', 'agendado'::public.match_status, null, null),
    ('group-g-5', 'G', 'NZL', 'BEL', '2026-06-26T23:00:00Z'::timestamptz, 'Lumen Field', 'Seattle', 'agendado'::public.match_status, null, null),
    ('group-g-6', 'G', 'EGY', 'IRN', '2026-06-26T23:00:00Z'::timestamptz, 'Lincoln Financial Field', 'Philadelphia', 'agendado'::public.match_status, null, null),
    ('group-h-5', 'H', 'URU', 'ESP', '2026-06-27T02:00:00Z'::timestamptz, 'BC Place', 'Vancouver', 'agendado'::public.match_status, null, null),
    ('group-h-6', 'H', 'CPV', 'KSA', '2026-06-27T02:00:00Z'::timestamptz, 'NRG Stadium', 'Houston', 'agendado'::public.match_status, null, null),
    ('group-l-5', 'L', 'PAN', 'ENG', '2026-06-27T19:00:00Z'::timestamptz, 'Lincoln Financial Field', 'Philadelphia', 'agendado'::public.match_status, null, null),
    ('group-l-6', 'L', 'CRO', 'GHA', '2026-06-27T19:00:00Z'::timestamptz, 'Lumen Field', 'Seattle', 'agendado'::public.match_status, null, null),
    ('group-j-5', 'J', 'JOR', 'ARG', '2026-06-27T23:00:00Z'::timestamptz, 'MetLife Stadium', 'New York/New Jersey', 'agendado'::public.match_status, null, null),
    ('group-j-6', 'J', 'ALG', 'AUT', '2026-06-27T23:00:00Z'::timestamptz, 'Arrowhead Stadium', 'Kansas City', 'agendado'::public.match_status, null, null),
    ('group-k-5', 'K', 'COL', 'POR', '2026-06-28T02:00:00Z'::timestamptz, 'Hard Rock Stadium', 'Miami', 'agendado'::public.match_status, null, null),
    ('group-k-6', 'K', 'COD', 'UZB', '2026-06-28T02:00:00Z'::timestamptz, 'Estadio BBVA', 'Monterrey', 'agendado'::public.match_status, null, null)
)
insert into public.matches (
  external_id,
  stage,
  group_name,
  home_team_id,
  away_team_id,
  home_score,
  away_score,
  status,
  kickoff_at,
  venue,
  city,
  raw_payload
)
select
  fixtures.external_id,
  'fase_de_grupos'::public.tournament_stage,
  fixtures.group_name,
  home_team.id,
  away_team.id,
  fixtures.home_score,
  fixtures.away_score,
  fixtures.status,
  fixtures.kickoff_at,
  fixtures.venue,
  fixtures.city,
  jsonb_build_object(
    'source', 'sbnation_2026_world_cup_schedule',
    'syncedAt', now(),
    'homeCode', fixtures.home_code,
    'awayCode', fixtures.away_code
  )
from fixtures
join public.teams home_team on home_team.external_id = fixtures.home_code
join public.teams away_team on away_team.external_id = fixtures.away_code
on conflict (external_id) do update set
  stage = excluded.stage,
  group_name = excluded.group_name,
  home_team_id = excluded.home_team_id,
  away_team_id = excluded.away_team_id,
  home_score = excluded.home_score,
  away_score = excluded.away_score,
  status = excluded.status,
  kickoff_at = excluded.kickoff_at,
  venue = excluded.venue,
  city = excluded.city,
  raw_payload = excluded.raw_payload,
  updated_at = now();
